### ISSUE TITLE
can't wait for a release! looks super clean

### ISSUE THREAD

**Issue by arttuxd** [bacontsu/autofarmer#2]

**Comment by bacontsu** [comment]
imma launch it pretty soon, since i just got banned in growtopia and this program isn't very useful for me anymore

**Comment by arttuxd** [comment]
That's cool, Why did you get banned?

**Comment by bacontsu** [comment]
i uploaded this and mod saw it I guess, my in-game-name is literally bacontsu too lol. and its not detected by the anticheat don't worry, this is a form app and I don't think they could detect this

**Comment by bacontsu** [comment]
going to upload the source code, issa crap code but it shoulda works
