### ISSUE TITLE
where is the source

### ISSUE THREAD

**Issue by Enpax** [bacontsu/autofarmer#3]
where is the source

**Comment by bacontsu** [comment]
where u when when shoot

i was home eating doritos

source code is kil

no

**Comment by bacontsu** [comment]
aside from the joke, sorry, i will not share the source code, or might share it partially (iunno bout this). might be ended up the same as my multibox program

**Comment by Enpax** [comment]
> aside from the joke, sorry, i will not share the source code, or might share it partially (iunno bout this). might be ended up the same as my multibox program

scammmmmmmmur ?

**Comment by bacontsu** [comment]
> > aside from the joke, sorry, i will not share the source code, or might share it partially (iunno bout this). might be ended up the same as my multibox program
> 
> scammmmmmmmur ?

well its ok if you thinks like that, I cant give my source code because people will easily steals it. i can only provide virustotal data and cpu usage monitoring throughout the process

**Comment by Enpax** [comment]
> > > aside from the joke, sorry, i will not share the source code, or might share it partially (iunno bout this). might be ended up the same as my multibox program
> > 
> > 
> > scammmmmmmmur ?
> 
> well its ok if you thinks like that, I cant give my source code because people will easily steals it. i can only provide virustotal data and cpu usage monitoring throughout the process

i know its not virus but just share sourdce bruh

**Comment by bacontsu** [comment]
> > > > aside from the joke, sorry, i will not share the source code, or might share it partially (iunno bout this). might be ended up the same as my multibox program
> > > 
> > > 
> > > scammmmmmmmur ?
> > 
> > 
> > well its ok if you thinks like that, I cant give my source code because people will easily steals it. i can only provide virustotal data and cpu usage monitoring throughout the process
> 
> i know its not virus but just share sourdce bruh

i could ended up sharing it idk, atm im just afraid of skidders but i get falsely accused for the program being an virus. 2 virustotal scan showing different results, like literally opposite. i might upload it if the situation is being more worse

**Comment by bacontsu** [comment]
source code will be released soon
